// Generated by CoffeeScript 1.4.0
var data, errorHandler, jsonData, onInitiFileSystem, parseData, quota;

data = null;

jsonData = "";

parseData = function(bookmarksTree) {
  console.log("Parsed!");
  data = bookmarksTree;
  jsonData = JSON.stringify(bookmarksTree);
  return bookmarksTree;
};

chrome.bookmarks.getTree(parseData);

onInitiFileSystem = function(fileSystem) {
  console.log("File System initialiased");
  return fileSystem.root.getFile('bookmarks.json', {
    create: true
  }, function(fileEntry) {
    var fileURLDiv, url;
    url = fileEntry.toURL();
    fileURLDiv = document.getElementById("fileURL");
    fileURLDiv.appendChild(document.createTextNode(url));
    console.log(url);
    return fileEntry.createWriter(function(fileWriter) {
      var blob;
      fileWriter.onwriteend = function(e) {
        return console.log("Write Completed");
      };
      fileWriter.onerror = function(e) {
        return console.log("Write Failed: " + e.toString());
      };
      blob = new Blob([jsonData], {
        type: "text/plain"
      });
      return fileWriter.write(blob);
    }, errorHandler);
  }, errorHandler);
};

errorHandler = function(error) {
  return console.log(error.code);
};

quota = 5 * 1024 * 1024;

window.webkitRequestFileSystem(window.TEMPORARY, quota, onInitiFileSystem, errorHandler);
