// Generated by CoffeeScript 1.4.0
var data, jsonData, parseData;

data = null;

jsonData = "";

parseData = function(bookmarksTree) {
  console.log("Parsed!");
  data = bookmarksTree;
  jsonData = JSON.stringify(bookmarksTree);
  return bookmarksTree;
};

chrome.bookmarks.getTree(parseData);
